[package]
name = "plasma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.19"
log = "0.4"
android_logger = "0.10"
lazy_static = "1.4.0"

[lib]
crate_type = ["cdylib"]
